file(GLOB_RECURSE FILES ${TEST_WORKING_DIR}/**)
file(REMOVE ${FILES})
execute_process(COMMAND ${TEST_EXECUTABLE} RESULT_VARIABLE status)
if(status)
    MESSAGE(FATAL_ERROR "Test executing status: ${status}")
endif()