//
// Created by draen on 10.09.23.
//

#ifndef LLP_LAB_INCLUDE_PUBLIC_DOMAIN_SCHEMA_TABLE_SCHEMA_H
#define LLP_LAB_INCLUDE_PUBLIC_DOMAIN_SCHEMA_TABLE_SCHEMA_H

struct table_schema;

#endif // LLP_LAB_INCLUDE_PUBLIC_DOMAIN_SCHEMA_TABLE_SCHEMA_H
