//
// Created by draen on 08.09.23.
//

#ifndef LLP_LAB_INCLUDE_PUBLIC_STORAGE_TABLE_DATA_MANAGER_H
#define LLP_LAB_INCLUDE_PUBLIC_STORAGE_TABLE_DATA_MANAGER_H

struct table_data_manager;

#endif // LLP_LAB_INCLUDE_PUBLIC_STORAGE_TABLE_DATA_MANAGER_H
